#!/usr/bin/env python
# coding: utf-8

import sys
import json
import robot

def load_config(config_file):
    config = {}
    with open(config_file, 'r') as f:
        for line in f:
            line = line.rstrip() #removes trailing whitespace and '\n' chars

            if "=" not in line: continue #skips blanks and comments w/o =
            if line.startswith("#"): continue #skips comments which contain =

            k, v = line.split("=", 1)
            config[k] = v.replace("\"","")
    return config

def main(argv):
    print "starting."

    config = load_config(argv[0])

    botdata = robot.load_robot(argv[1],config['SMOOCHBOT_NAME'])

    if botdata:
        print "loading robot {0}.".format(argv[1])
    else:
        print "could not find robot {0}.".format(argv[1])
        sys.exit(1)

    bot = robot.Robot(botdata)
    bot.process_input("input")

    print "{0} loaded.".format(argv[1])

    listening = True
    while listening:
        line = sys.stdin.readline()

        if not line:
            break
        else:
            if(":q" in line):
                print "goodbye."
                break
            sys.stdout.write("user: {0}".format(line))
            response = bot.process_input(line)
            print "robot: {0}".format(response)


if __name__ == "__main__":
    main(sys.argv[1:])
